name: Run Python Script on Issue Approved

on:
  issues:
    types: [labeled]

jobs:
  run-python-script:
    # only when the *added* label is exactly "approved"
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'approved' }}
    runs-on: [self-hosted, juist-hosted]

    steps:
      - name: Debug event
        run: |
          echo "action=${{ github.event.action }}"
          echo "added_label=${{ github.event.label.name }}"
          echo 'all_labels=${{ toJson(github.event.issue.labels.*.name) }}'

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your Python script
        run: echo "Works"
