name: Process Approved Issue

on:
  issues:
    types: [labeled]

permissions:
  issues: read
  contents: read

jobs:
  run-on-approved:
    if: contains(join(github.event.issue.labels.*.name, ' '), 'approved')
    runs-on: [self-hosted, juist-hosted]

    concurrency:
      group: issue-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Check out workflow repo (optional, if you need code)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Save issue body to file
        id: save_body
        run: |
          printf "%s" "${{ github.event.issue.body }}" > issue_body.txt

      - name: Extract YAML from issue body
        id: extract_yaml
        run: |
          python scripts/extract_yaml.py issue_body.txt payload.yaml

      - name: Validate YAML schema (optional but recommended)
        run: |
          pip install voluptuous
          python scripts/validate_yaml.py payload.yaml

      - name: Run your business logic
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          python scripts/run_pipeline.py payload.yaml

      - name: (Optional) Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.event.issue.number }}
          path: outputs/
          if-no-files-found: ignore

      - name: (Optional) Comment back on the issue
        uses: actions/github-script@v7
        with:
          script: |
            const number = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: "✅ Processing finished for this approved submission."
            });
