name: Process Approved Issues

on:
  issues:
    types: [labeled]

jobs:
  process:
    if: contains(join(github.event.issue.labels.*.name, ' '), 'approved')
    runs-on: [self-hosted, linux, juist-hosted]

    steps:
      - name: Start
        run: echo "🚀 Starting pipeline for issue #${{ github.event.issue.number }}"

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo "==> Installing dependencies"
          python -m pip install --upgrade pip
          pip install pyyaml
          echo "✅ Dependencies installed"

      - name: Save issue body
        run: |
          echo "==> Writing issue body to file"
          printf "%s" "${{ github.event.issue.body }}" > issue_body.txt
          ls -lh issue_body.txt
          echo "✅ Done"

      - name: Extract YAML
        run: |
          echo "==> Extracting YAML"
          python scripts/extract_yaml.py issue_body.txt payload.yaml
          echo "YAML content:"
          cat payload.yaml
          echo "✅ YAML extracted"

      - name: Run pipeline
        run: |
          echo "==> Running pipeline script"
          python scripts/run_pipeline.py payload.yaml
          echo "✅ Pipeline finished"

      - name: Done
        run: echo "🎉 All steps completed successfully"
