name: Run Python Script on Issue Approved

on:
  issues:
    types: [labeled]

jobs:
  run-python-script:
    # Works if 'approved' label is present in the issue labels
    if: contains(github.event.issue.labels.*.name, 'approved')
    runs-on: [self-hosted, juist-hosted]

    steps:
      - name: Dump event context
        run: echo "${{ toJson(github.event) }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run your Python script
        run: echo "Works"


